version: '3.9'

services:
  backend:
    build: ./app
    container_name: flask-app
    env_file:
      - .env
    ports:
      - '8001:8000'
    command: sh -c 'flask run --host=0.0.0.0 --port=8001'

    depends_on:
      - neo4j
    networks:
      - app_net

  neo4j:
    image: neo4j:5.10
    container_name: neo4j-db
    environment:
      - NEO4J_AUTH=neo4j/testtest
    ports:
      - '7474:7474'
      - '7687:7687'

    volumes:
      - neo4j_data:/data
    networks:
      - app_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - app_net

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - '3001:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - app_net


volumes:
  neo4j_data:

networks:
  app_net:
    driver: bridge